apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: yamazawa@supersoftware.co.jp
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}

---

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kubernetes-cf-prod
spec:
  secretName: kubernetes-cf-tls-prod
  issuerRef:
    name: letsencrypt-prod
  commonName: kubernetes.cf
  dnsNames:
  - example.kubernetes.cf
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - kubernetes.cf
    - http01:
        ingress: nginx
      domains:
      - example.kubernetes.cf