apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: 51.15.39.110
    external-dns.alpha.kubernetes.io/target: 51.15.85.186
spec:
  tls:
  - hosts:
    - kubernetes.cf
    - example.kubernetes.cf
    secretName: kubernetes-cf-tls-prod
  rules:
  - host: kubernetes.cf
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
  - host: example.kubernetes.cf
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
