apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: default
  namespace: default

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exeternal-dns
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - name: external-dns
        image: yamazawa/external-dns:coredns
        args:
        - --source=ingress
        - --namespace=default
        - --domain-filter=kubernetes.cf
        - --provider=coredns
        - --registry=txt
        - --txt-owner-id=default.kubernetes.cf
        - --log-level=debug
        env:
        - name: ETCD_URLS
          value: http://example-etcd-cluster-client.default.svc.cluster.local:2379
