apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: weave
  namespace: weave
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: weave.service.op
    http:
      paths:
      - path: /weave
        backend:
          serviceName: weave-scope-app
          servicePort: 80
